spring.application.name=urlShortner
allowed.origins=http://localhost:5173,http://localhost:3000,https://your-production-url.com

## ================= Postgres Configuration =================
spring.datasource.url=jdbc:postgresql://{your_host}:{port}/{db_name}
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

## ================= Redis Configuration =================
spring.data.redis.host=your_host
spring.data.redis.port=port

## ================= Kafka Configuration =================
spring.kafka.bootstrap-servers=your_host:port

## ================= Producer config =================
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

## ================= Consumer config =================
spring.kafka.consumer.group-id=analytics-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer